name: wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]
    env:
      BUILD_WITH_ACPC: ON
      BUILD_WITH_HANABI: ON
      CIBW_PROJECT_REQUIRES_PYTHON: ">=3.6"
      OS_PYTHON_VERSION: 3.9

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install
        run: |
          pwd
          chmod +x install.sh
          ./install.sh
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools
          python3 -m pip install twine build
          python3 -m pip install cibuildwheel==1.10.0

      - name: Build sdist
        run: |
          python3 -m build -s
          twine check dist/*.tar.gz
          
      - name: Build bdist_wheel
        run: |
          python3 -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: |
            dist/*.tar.gz
            ./wheelhouse/*.whl
